# Config for Migration of data in tables
tables:
  - name: nastaveni
    primaryKey: key
    columns:
      - name: value
        target: jsonb
        targetConfig: "nastaveni" # contains value and className in jsonb
  - name: sms_history
    primaryKey: id
    columns:
      - name: groups
        target: jsonb
        targetConfig: "list"
      - name: recipients
        target: jsonb
        targetConfig: "list"
      - name: morerecipients
        target: jsonb
        targetConfig: "list"
  - name: email_history
    primaryKey: id
    columns:
      - name: groups
        target: jsonb
        targetConfig: "list"
      - name: recipients
        target: jsonb
        targetConfig: "list"
      - name: morerecipients
        target: jsonb
        targetConfig: "list"
      - name: attachments
        target: filesystem
        targetConfig: "attachments"  # base dir in FileSystem - rename to some number contains FileName and FilePath
  - name: generated_attachment
    primaryKey: id
    columns:
      - name: attributes
        target: jsonb
        targetConfig: "attributes" # contains value and Key in jsonb (Map<String,Object>)
  - name: instructor
    primaryKey: id
    columns:
      - name: photo
        target: filesystem
        targetConfig: "photo" # base dir in FileSystem - rename to some number contains FileName and FilePath
  - name: objekt
    primaryKey: id
    columns:
      - name: reservationstart
        target: jsonb
        targetConfig: "list"
      - name: reservationfinish
        target: jsonb
        targetConfig: "list"
  - name: omezeni_rezervaci
    primaryKey: objektId
    columns:
        - name: omezeni
          target: jsonb
          targetConfig: "jsonObject"